version: '3.9'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - rede_eletrica

  empresa_a:
    build:
      context: ./empresa_a
    container_name: empresa_a
    ports:
      - "8000:8000"
    volumes:
      - ./empresa_a:/app
    environment:
      - EMPRESA_NOME=Empresa A
      - EMPRESA_LOCAL=João Pessoa
      - EMPRESA_PONTOS=["JP1", "MC1"]
    networks:
      - rede_eletrica

  empresa_b:
    build:
      context: ./empresa_b
    container_name: empresa_b
    ports:
      - "8001:8000"
    volumes:
      - ./empresa_b:/app
    environment:
      - EMPRESA_NOME=Empresa B
      - EMPRESA_LOCAL=Maceió
      - EMPRESA_PONTOS=["MC2", "SE1"]
    networks:
      - rede_eletrica

  empresa_c:
    build:
      context: ./empresa_c
    container_name: empresa_c
    ports:
      - "8002:8000"
    volumes:
      - ./empresa_c:/app
    environment:
      - EMPRESA_NOME=Empresa C
      - EMPRESA_LOCAL=Sergipe
      - EMPRESA_PONTOS=["SE2", "FS1"]
    networks:
      - rede_eletrica

  carro1:
    build:
      context: ./carro
    container_name: carro1
    depends_on:
      - empresa_a
      - empresa_b
      - empresa_c
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    networks:
      - rede_eletrica

  simulador:
    build:
      context: ./carro
    container_name: simulador
    depends_on:
      - empresa_a
      - empresa_b
      - empresa_c
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1
    command: python simulador_carros.py
    networks:
      - rede_eletrica

networks:
  rede_eletrica: