version: '3.9'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports: ["1883:1883"]
  empresa_a:
    build: .
    container_name: empresa_a
    ports: ["8000:8000"]
    volumes:
      - ./app:/app
    environment:
      - EMPRESA_NOME=Empresa A 
      - EMPRESA_LOCAL=João Pessoa
      - EMPRESA_PONTOS=["JP1", "MC1"]
  
  empresa_b:
    build: .
    container_name: empresa_b
    ports: ["8001:8000"]
    volumes:
      - ./app:/app
    environment:
      - EMPRESA_NOME=Empresa B 
      - EMPRESA_LOCAL=Maceió
      - EMPRESA_PONTOS=["MC2", "SE1"]
  
  empresa_c:
    build: .
    container_name: empresa_c
    ports: ["8002:8000"]
    volumes:
      - ./app:/app
    environment:
      - EMPRESA_NOME=Empresa C 
      - EMPRESA_LOCAL=Sergipe
      - EMPRESA_PONTOS=["SE2", "FS1"]
